### PR TITLE
Add androidx support to avoid errors of annotations

### PR DESCRIPTION
**Pull request by JIBIN-P**
Hii, I had to use jetify to get this suggestion to raise a PR basically if the following changes are not made i get an error about annotation so after much troubleshooting git to know about jetify and got it fixed. Hope this is helpful.

### CODE REVIEW

**Comment by JIBIN-P** [comment]
Hii @hanatharesh2712 can you please take a look at this?

**Comment by hanatharesh2712** [comment]
> Hii @hanatharesh2712 can you please take a look at this?

I have tested the plugin with Android version 30 and it works well. without AndroidX support. and Android version 31 is in beta and will test later for that. I don't want to add a dependency for Androidx in the plugin for now as not required.
But, In future If it is really required then will merge your PR.

Thanks for making PR!

**Comment by blackram** [comment]
On Android 9 now, and import android.support.annotation.NonNull is legacy. 

We are going to either have to fork to use the androidx namepsace or use a plugin like cordova plugin add cordova-plugin-androidx-adapter

https://stackoverflow.com/questions/63831903/im-getting-the-androidx-dependencies-error-with-android-useandroidx-enabled

**Comment by hanatharesh2712** [comment]
@blackram @JIBIN-P I will merge the PR and do some tests on this.. then will merge it. Thanks!

**Comment by blackram** [comment]
Thanks!

**Comment by hanatharesh2712** [comment]
@JIBIN-P I have updated the package and removed the android.support.annotation.NonNull import as it is not required. Thanks

**Pull request closed without merging**
